export enum OrderStatus {
  PENDING_PROPOSALS = 'PENDING_PROPOSALS',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REVIEWED = 'REVIEWED',
}
